### PR TITLE
Added Pieter Jonckiere to the cool kids

### PR DESCRIPTION
**Pull request by pjonckiere**

### CODE REVIEW

**Comment by geertvd** [comment]
please reroll

**Comment by pjonckiere** [comment]
Simple reroll.

**Comment by geertvd** [comment]
I think we need some discussion on this one

**Comment by marieke-h** [comment]
I don't think we're ready for this one.

**Comment by pjonckiere** [comment]
Never mind. I'll close this issue and be a cool kid on my own.

**Pull request closed without merging**
