### PR TITLE
Please add pjbaert to the README.md file

### PR DESCRIPTION
**Pull request by pjbaert**
Fixed

### CODE REVIEW

**Comment by geertvd** [comment]
please reroll

**Comment by geertvd** [comment]
please add a clear title

**Comment by marieke-h** [comment]
I don't think pjbaert should be added to the coole_kindjes.

**Comment by pjbaert** [comment]
http://img2.wikia.nocookie.net/__cb20140223041635/breadwinnersnick/images/b/b8/Please.jpg

**Comment by geertvd** [comment]
We should re-open this one and have more discussion on it.
It seems PJ is not very fond of our furry little friends. How should we resolve this?

**Comment by pjbaert** [comment]
How could you say that?! 
I even added a picture of a kitten to my comment above.

**Pull request merged**
